pr test

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -48,11 +48,31 @@ jobs:
         run: |
           black .
           isort .
+        id: format_code
+      #    git config --global user.name "GitHub Actions"
+      #    git config --global user.email "actions@github.com"
+      #    git commit -am "Apply code formatting with Black and isort" || echo "No changes to commit"
+      # - name: Push changes
+      #   if: failure()
+      #   uses: ad-m/github-push-action@v0.6.0
+      #   with:
+      #     github_token: ${{ secrets.GITHUB_TOKEN }}
+      - name: Create and Push Branch (if changes)
+        if: ${{ steps.format_code.outcome == 'success' }}
+        run: |
           git config --global user.name "GitHub Actions"
           git config --global user.email "actions@github.com"
-          git commit -am "Apply code formatting with Black and isort" || echo "No changes to commit"
-      - name: Push changes
-        if: failure()
-        uses: ad-m/github-push-action@v0.6.0
+          git checkout -b lint-fix/${{ github.run_id }}
+          git add .
+          git commit -m "style: auto-format code by linter"
+          git push origin lint-fix/${{ github.run_id }}
+
+      - name: Create Pull Request
+        uses: peter-evans/create-pull-request@v5
         with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+          token: ${{ secrets.GITHUB_TOKEN }}
+          branch: lint-fix/${{ github.run_id }}
+          base: ${{ github.ref_name}}  # Ursprungsbranch
+          title: "style: auto-format code"
+          body: |
+            This pull request applies automatic formatting to the codebase.
